version: '3.8'

services:
  # PostgreSQL with PgVector
  postgres:
    image: docker.m.daocloud.io/pgvector/pgvector:pg16
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magicain"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - magicain-infra

  # Redis
  redis:
    image: docker.m.daocloud.io/redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server --appendonly yes --requirepass ${REDIS_AUTH}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - magicain-infra
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TCP_PORT}:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - magicain-infra

  # ClickHouse - Analytics Database
  clickhouse:
    image: docker.m.daocloud.io/clickhouse/clickhouse-server:latest
    restart: unless-stopped
    user: "101:101"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./database/clickhouse/init:/docker-entrypoint-initdb.d
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_TCP_PORT}:9000"
    networks:
      - magicain-infra
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s

volumes:
  postgres_data:
  redis_data:
  es_data:
  clickhouse_data:
  clickhouse_logs:

networks:
  magicain-infra:
    driver: bridge