global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: /metrics

  # Backend Java application metrics (Spring Boot Actuator)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 10s

  # PostgreSQL metrics (if postgres-exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics (if redis-exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Elasticsearch metrics (if elasticsearch-exporter is added)
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: /metrics
    scrape_interval: 30s

  # Langfuse metrics (if available)
  - job_name: 'langfuse'
    static_configs:
      - targets: ['langfuse:3000']
    metrics_path: /api/public/metrics
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics

  # Custom application metrics
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: /api/metrics
    scrape_interval: 30s